#import "../../components.typ": authored_by

== Optimierung
#authored_by("Florian Weichert")
Obwohl das Frameraten-Ziel für dieses Projekt ursprünglich bei 25 Bilder pro Sekunde #footnote[Nachfolgend als fps, frames per second, bezeichnet.] lag #footnote[Europäischer Film hat typischerweise eine Framerate von 25 Bildern pro Sekunde, da diese früher von der Frequenz des europäischen Strom-Netzes, also 50hz, abhängig waren.], musste schlussendlich eine Framerate von 30 fps erreicht werden, da die verwendete Capture-Card nur diese oder 60 fps unterstützt. So ergibt sich ein maximales Zeit-Budget pro Frame von 33,33 ms. Zum Ende der Implementierungsphase wurde jedoch für die Berechnung jedes Frames eine Zeit von durchschnittlich \~37 ms#footnote[Die Zeitangabe wurde auf einem MacBook mit Apple M1 Pro Prozessor gemessen.]<fn:timings-refer-to-m1-pro> benötigt. Also mussten Optimierungen vorgenommen werden, sodass keine Frame-Drops entstehen. Um einen besseren Einblick in die Performance der einzelnen Effekte zu erhalten, wurden die Durchlaufzeiten der Effekte jeweils einzeln gemessen (@fig:frame-timings).

#figure(
  image("../../assets/processing-times.png"),
  caption: [Durchlaufzeiten @fn:timings-refer-to-m1-pro der einzelnen Effekte],
)<fig:frame-timings>

Besonders auffällig bei diesen Werten ist, dass der Effekt Halation mit \~19 ms @fn:timings-refer-to-m1-pro mit Abstand die längste Durchlaufzeit hat. Dieser Effekt wurde daraufhin genauer untersucht, dabei fiel auf, dass die Berechnung des Gaußschen Weichzeichners mit \~17 ms @fn:timings-refer-to-m1-pro den Großteil der Verarbeitungszeit in Anspruch nimmt.
#parbreak()
Ein Ansatz die Performance zu verbessern ist die Verwendung eines anderen Weichzeichners, der weniger Rechenleistung benötigt. Eine gängige Option ist der Box-Weichzeichner. Dieser hat jedoch den Nachteil, dass er durch seinen rechteckigen, gleichförmigen Kernel nicht besonders weich wirkt. In diesem Fall wäre die Verwendung eines Box-Filters daher ein besonders großes Problem, da als Ziel ein besonders natürlicher Look angestrebt wird. Eine andere Option ist es, den Rechenaufwand für den Gaußschen Weichzeichner zu reduzieren. Wird das Eingabebild zunächst auf eine wesentlich kleinere Größe skaliert, muss der Weichzeichner nicht nur weniger Pixel berechnen, sondern auch der Gaußsche-Kernel muss bei gleichbleibender relativer Größe im Vergleich zum Eingabebild weniger Pixel umfassen. Dieser Ansatz wurde in der Implementierung umgesetzt und führte zu einer signifikanten Verbesserung der Performance. Die Durchlaufzeit des Effekts Halation konnte so von \~19 ms @fn:timings-refer-to-m1-pro auf \~4 ms @fn:timings-refer-to-m1-pro reduziert werden. Die Gesamtdurchlaufzeit aller Effekte konnte so auf durchschnittlich \~22 ms @fn:timings-refer-to-m1-pro gesenkt werden. Allein durch diese Anpassung konnte das Zeit-Budget mit reichlich Spielraum eingehalten werden.